; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG2969	DB	'Ethernet ARP : Packet received ', 0dH, 0aH, 00H
	ORG $+6
$SG2971	DB	'Ethernet IPv4: Packet received ', 0dH, 0aH, 00H
	ORG $+6
$SG2985	DB	'Ethernet setuped %d %s', 0dH, 0aH, 00H
	ORG $+7
$SG2988	DB	'HWFile writing %x ', 0dH, 0aH, 00H
CONST	ENDS
PUBLIC	?AuEthernetSend@@YAXPEAX_KGPEAE@Z		; AuEthernetSend
PUBLIC	AuEthernetHandle
EXTRN	AuGetNetworkAdapterByType:PROC
EXTRN	kmalloc:PROC
EXTRN	kfree:PROC
EXTRN	memset:PROC
EXTRN	memcpy:PROC
EXTRN	SeTextOut:PROC
EXTRN	AuTextOut:PROC
pdata	SEGMENT
$pdata$?AuEthernetSend@@YAXPEAX_KGPEAE@Z DD imagerel $LN6
	DD	imagerel $LN6+340
	DD	imagerel $unwind$?AuEthernetSend@@YAXPEAX_KGPEAE@Z
$pdata$AuEthernetHandle DD imagerel $LN7
	DD	imagerel $LN7+103
	DD	imagerel $unwind$AuEthernetHandle
pdata	ENDS
xdata	SEGMENT
$unwind$?AuEthernetSend@@YAXPEAX_KGPEAE@Z DD 011901H
	DD	08219H
$unwind$AuEthernetHandle DD 010901H
	DD	06209H
xdata	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\aurora\kernel\net\ethernet.cpp
_TEXT	SEGMENT
tv73 = 32
frame$ = 64
AuEthernetHandle PROC

; 37   : AU_EXTERN AU_EXPORT void AuEthernetHandle(Ethernet *frame) {

$LN7:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 38   : 	switch (ntohs(frame->typeLen)) {

	mov	rax, QWORD PTR frame$[rsp]
	movzx	eax, WORD PTR [rax+12]
	and	eax, 255				; 000000ffH
	shl	eax, 8
	mov	rcx, QWORD PTR frame$[rsp]
	movzx	ecx, WORD PTR [rcx+12]
	and	ecx, 65280				; 0000ff00H
	sar	ecx, 8
	or	eax, ecx
	mov	DWORD PTR tv73[rsp], eax
	cmp	DWORD PTR tv73[rsp], 2048		; 00000800H
	je	SHORT $LN1@AuEthernet
	cmp	DWORD PTR tv73[rsp], 2054		; 00000806H
	je	SHORT $LN2@AuEthernet
	jmp	SHORT $LN3@AuEthernet
$LN2@AuEthernet:

; 39   : 	case ETHERNET_TYPE_ARP:
; 40   : 		SeTextOut("Ethernet ARP : Packet received \r\n");

	lea	rcx, OFFSET FLAT:$SG2969
	call	SeTextOut

; 41   : 		break;

	jmp	SHORT $LN3@AuEthernet
$LN1@AuEthernet:

; 42   : 	case ETHERNET_TYPE_IPV4:
; 43   : 		SeTextOut("Ethernet IPv4: Packet received \r\n");

	lea	rcx, OFFSET FLAT:$SG2971
	call	SeTextOut
$LN3@AuEthernet:

; 44   : 		break;
; 45   : 	}
; 46   : }

	add	rsp, 56					; 00000038H
	ret	0
AuEthernetHandle ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
; File e:\xeneva project\aurora\kernel\net\ethernet.cpp
_TEXT	SEGMENT
netadapt$ = 32
pacl$ = 40
totalSz$ = 48
src_mac$ = 56
data$ = 80
len$ = 88
type$ = 96
dest$ = 104
?AuEthernetSend@@YAXPEAX_KGPEAE@Z PROC			; AuEthernetSend

; 55   : void AuEthernetSend(void* data, size_t len, uint16_t type, uint8_t* dest) {

$LN6:
	mov	QWORD PTR [rsp+32], r9
	mov	WORD PTR [rsp+24], r8w
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 56   : 	AuNetAdapter* netadapt = AuGetNetworkAdapterByType(AUNET_HWTYPE_ETHERNET);

	mov	cl, 1
	call	AuGetNetworkAdapterByType
	mov	QWORD PTR netadapt$[rsp], rax

; 57   : 	if (!netadapt)

	cmp	QWORD PTR netadapt$[rsp], 0
	jne	SHORT $LN3@AuEthernet

; 58   : 		return;

	jmp	$LN4@AuEthernet
$LN3@AuEthernet:

; 59   : 	size_t totalSz = sizeof(Ethernet)+len;

	mov	rax, QWORD PTR len$[rsp]
	add	rax, 14
	mov	QWORD PTR totalSz$[rsp], rax

; 60   : 	Ethernet* pacl = (Ethernet*)kmalloc(totalSz);

	mov	ecx, DWORD PTR totalSz$[rsp]
	call	kmalloc
	mov	QWORD PTR pacl$[rsp], rax

; 61   : 	memset(pacl, 0, totalSz);

	mov	r8d, DWORD PTR totalSz$[rsp]
	xor	edx, edx
	mov	rcx, QWORD PTR pacl$[rsp]
	call	memset

; 62   : 	memcpy(pacl->dest, dest, 6);

	mov	rax, QWORD PTR pacl$[rsp]
	mov	r8d, 6
	mov	rdx, QWORD PTR dest$[rsp]
	mov	rcx, rax
	call	memcpy

; 63   : 	uint8_t *src_mac = netadapt->mac;

	mov	rax, QWORD PTR netadapt$[rsp]
	mov	QWORD PTR src_mac$[rsp], rax

; 64   : 	memcpy(pacl->src, src_mac, 6);

	mov	rax, QWORD PTR pacl$[rsp]
	add	rax, 6
	mov	r8d, 6
	mov	rdx, QWORD PTR src_mac$[rsp]
	mov	rcx, rax
	call	memcpy

; 65   : 	pacl->typeLen = htons(type);

	movzx	eax, WORD PTR type$[rsp]
	and	eax, 255				; 000000ffH
	shl	eax, 8
	movzx	ecx, WORD PTR type$[rsp]
	and	ecx, 65280				; 0000ff00H
	sar	ecx, 8
	or	eax, ecx
	mov	rcx, QWORD PTR pacl$[rsp]
	mov	WORD PTR [rcx+12], ax

; 66   : 	AuTextOut("Ethernet setuped %d %s\r\n", netadapt->type, netadapt->name);

	mov	rax, QWORD PTR netadapt$[rsp]
	add	rax, 6
	mov	rcx, QWORD PTR netadapt$[rsp]
	movzx	ecx, BYTE PTR [rcx+22]
	mov	r8, rax
	mov	edx, ecx
	lea	rcx, OFFSET FLAT:$SG2985
	call	AuTextOut

; 67   : 	if (!netadapt->hwFile)

	mov	rax, QWORD PTR netadapt$[rsp]
	cmp	QWORD PTR [rax+14], 0
	jne	SHORT $LN2@AuEthernet

; 68   : 		return;

	jmp	SHORT $LN4@AuEthernet
$LN2@AuEthernet:

; 69   : 	if (netadapt->hwFile->write) {

	mov	rax, QWORD PTR netadapt$[rsp]
	mov	rax, QWORD PTR [rax+14]
	cmp	QWORD PTR [rax+87], 0
	je	SHORT $LN1@AuEthernet

; 70   : 		SeTextOut("HWFile writing %x \r\n",netadapt->hwFile->write );

	mov	rax, QWORD PTR netadapt$[rsp]
	mov	rax, QWORD PTR [rax+14]
	mov	rdx, QWORD PTR [rax+87]
	lea	rcx, OFFSET FLAT:$SG2988
	call	SeTextOut

; 71   : 		netadapt->hwFile->write(netadapt->hwFile, netadapt->hwFile, (uint64_t*)pacl, totalSz);

	mov	rax, QWORD PTR netadapt$[rsp]
	mov	rax, QWORD PTR [rax+14]
	mov	r9d, DWORD PTR totalSz$[rsp]
	mov	r8, QWORD PTR pacl$[rsp]
	mov	rcx, QWORD PTR netadapt$[rsp]
	mov	rdx, QWORD PTR [rcx+14]
	mov	rcx, QWORD PTR netadapt$[rsp]
	mov	rcx, QWORD PTR [rcx+14]
	call	QWORD PTR [rax+87]
$LN1@AuEthernet:

; 72   : 	}
; 73   : 	kfree(pacl);

	mov	rcx, QWORD PTR pacl$[rsp]
	call	kfree
$LN4@AuEthernet:

; 74   : }

	add	rsp, 72					; 00000048H
	ret	0
?AuEthernetSend@@YAXPEAX_KGPEAE@Z ENDP			; AuEthernetSend
_TEXT	ENDS
END
