name: XenevaOS Build Check (LLVM/Clang AArch64)

on:
  push:
    branches: [ master, khrsgr ]
  pull_request:
    branches: [ master, khrsgr ]
  workflow_dispatch:

jobs:
  build-llvm-aarch64:
    name: LLVM/Clang (Linux / AArch64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld make mtools dosfstools

      - name: Clone gnu-efi
        run: git clone --depth 1 https://github.com/vathpela/gnu-efi.git

      - name: Build Bootloader (BootAA64)
        run: make -C BootAA64 llvm

      - name: Build Kernel (KernelAA64)
        run: make -C KernelAA64 llvm
